name: nebular
on:
  workflow_call:
  
jobs:
  build_and_test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:packages
      - uses: actions/upload-artifact@v2
        with:
          name: built-packages
          path: 'dist/'
          retention-days: 1       
  build-playground:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: built-packages
          path: dist
      - run: npm run build playground -- --configuration=production-wp    
      
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: |
              dist
              package.json
              
  unit-test:
    needs: build-playground
    runs-on: ubuntu-latest
    env:
      BSU: debac1
      BSK: AhrdZMi5gFDy3CQQfJHs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: built-packages
          path: dist
      - name: BrowserStack Setup
        uses: 'browserstack/github-actions@master'
        with:
          username: ${{ env.BSU }}
          access-key: ${{ env.BSK }}
      - name: Start BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
      - name: Test packages
        run: npm run test playground -- -c=production-wp --watch=false
      - name: Test schematics
        run: npm run test:schematics
      - name: Stop BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
